# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project_3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'MFCard'
  # Pods for Project_3

  target 'Project_3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Project_3UITests' do
    # Pods for testing
  end

end
